name: 🚀 Deploy PROD to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🔐 Préparer la clé SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/${{ secrets.VPS_SSH_KEY_NAME }}
          chmod 600 ~/.ssh/${{ secrets.VPS_SSH_KEY_NAME }}
          ssh-keyscan -p ${{ secrets.VPS_PORT }} -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: 🚀 Déploiement SSH
        run: |
          ssh -i ~/.ssh/${{ secrets.VPS_SSH_KEY_NAME }} \
              -p ${{ secrets.VPS_PORT }} \
              -o StrictHostKeyChecking=no \
              ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e

            echo "✅ Connexion SSH réussie"
            mkdir -p ~/projects/LaStationBot/prod
            cd ~/projects/LaStationBot/prod

            if [ ! -d ".git" ]; then
              echo "📁 Clonage initial"
              git clone -b main https://github.com/jordan-olv/la-station.git .
            fi

            echo "📥 Synchronisation avec origin/main"
            git fetch --prune origin main
            git reset --hard origin/main
            git clean -fd

            echo "🔧 Ajustement des droits"
            chown -R deploy:deploy ~/projects/LaStationBot/prod

            echo "🛠 Backend – install & build"
            npm install
            npm run build

            echo "🛠 Frontend – install & build"
            cd src/frontend
            npm install
            npm run build
            cd ..

            echo "🚀 PM2 Reload all apps via ecosystem"
            pm2 delete la-station-bot la-station-front || true
            pm2 start ecosystem.config.cjs
            pm2 save

            echo "✅ Déploiement PROD terminé 🎉"
          EOF
